[36;1mSaving config:
[0m
{
    "K_epochs":	5,
    "action_dim":	2,
    "actor_dim":	[
        64,
        64
    ],
    "actor_lr":	0.0003,
    "algo_name":	"ppo",
    "critic_dim":	[
        128,
        128
    ],
    "critic_lr":	0.0005,
    "device":	"cuda:0",
    "entropy_scaler":	0.001,
    "episode_len":	200,
    "eps":	0.2,
    "eval_episodes":	10,
    "eval_num":	10,
    "gae":	0.95,
    "gamma":	0.99,
    "gpu_idx":	0,
    "group":	"03-17_19-04-58.754753-b2ba",
    "load_pretrained_model":	false,
    "log_intervals":	10,
    "logdir":	"log/train_log/03-17_19-04-58.754753-b2ba",
    "minibatch_size":	512,
    "name":	"ppo-car-b2ba-seed:1825",
    "num_minibatch":	10,
    "num_runs":	10,
    "project":	"Exp",
    "seed":	1825,
    "state_dim":	4,
    "target_kl":	0.02,
    "task":	"car",
    "timesteps":	100000.0,
    "use_cuda":	true
}
PPO Training (Timesteps):  10%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñè                                                                                                                                                                                                                                                                                         | 10240/100000.0 [00:03<00:32, 2795.79it/s]
Traceback (most recent call last):
  File "/home/minjae/research/RLCM/main.py", line 196, in <module>
    run(args, seed, unique_id, exp_time)
  File "/home/minjae/research/RLCM/main.py", line 176, in run
    trainer.train()
  File "/home/minjae/research/RLCM/trainer/online_trainer.py", line 100, in train
    self.write_image(
TypeError: Trainer.write_image() got an unexpected keyword argument 'logdir'
